language: go
sudo: false
dist: bionic
go: 1.13.x

notifications:
  email: false

stages:
  - name: build
    if: type = push
  - name: presubmits
    if: type = pr OR branch = master OR tag IS present
  - name: deploy
    if: type = push AND tag IS present

jobs:
  include:
    - stage: build
      install: skip
      script: make

    - stage: presubmits
      name: Generate, Format, and Lint
      install:
        - make tools
      script:
        - make gen
        - bin/files-changed proto
        - make format
        - bin/files-changed format
        - make lint

    - &build
      name: Build and Unit Tests
      install: skip
      script:
        - go build github.com/google/fscrypt/cmd/fscrypt
        - make

    - <<: *build
      go: 1.12.x
      env: GO111MODULE=on

    - name: Integration Tests
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: 'deb http://en.archive.ubuntu.com/ubuntu/ artful main universe'
          packages:
            - e2fsprogs
      install:
        - go get -u github.com/mattn/goveralls
        - make test-setup
      script:
        - make coverage.out
        - goveralls -coverprofile=coverage.out -service=travis-ci

    - stage: deploy
      name: Release Binaries
      install: skip
      script: skip
      before_deploy: make
      deploy:
        - provider: releases
          api_key:
            secure: aq1sQacqogyjSaf8WJxorVEnXXe1TRz2gl6eoTDuMZVD7fyBV2cgyKgSX3kVt4DZlBTQWlagQQqEluOp6brSQVt2AzLLGPVtUN286M6dN8tSSenn3qDRS5UYyUIhg8KvtqOD6ItFlibCA+7t5B+j4KCCgAKBkDSORJoS180hUbsC6lOx/F/yhjMUTBq96NloIrk7N33JdOjQfeRKiEXZcbRsntzwJlmUjdGLxjIDI409Dx/oDh2rqXz/sJ98ljXebKa28ObyQW9f2UsIBGyFBOnUMK47neJqve/pjGWp1p8pyIGM9rsy+kAQ9htRARcYbBTwTavOCXRehMS+muqttI66G69teHkNfo/dSp52esmNi0p7SQJOydHFJ3gy9alYH4MHGCHnrRdcKnGPyAk3KcsCMxFehPx3pHMShrxh+x9tQz87G1FZlNpyiZiq5fHtb7IDV8l+0XaJKrNhCDvrBwNh8w7iQsAXapmk2Hn8UGTAWbKxCL1l4afB5LA6IGNISmEMuylhnaFZU2WvFzdO7iKY43TePaZJbmMtvovkOVuOWEqxgrkLMXsYrgx0bSV2UCVXJG3XEeJtQluwQgeEYeH6d9VR/chcQ4Qii99IzwbFk2iAk3RN3N94JWT+ubRhJUISOvZ8Z9OMSUBi517mxNgE1HxYa5AadiMQlKVUbDE=
          file:
            - bin/fscrypt
            - bin/pam_fscrypt.so
          skip_cleanup: true
          on:
            repo: google/fscrypt
            branch: master
            tags: true
